language: python
python: 3.9
sudo: required

script:
  - echo "DONE"

after_success:
  - docker login --username $HEROKU_DOCKER_USERNAME --password $HEROKU_API_KEY registry.heroku.com
  - docker build -t flask-zhaw:latest .
  - docker tag flask-zhaw:latest registry.heroku.com/$HEROKU_APP_NAME/web
  - docker push registry.heroku.com/$HEROKU_APP_NAME/web
  - heroku container:release web --app $HEROKU_APP_NAME